### PR TITLE
Reverting changes to 'deployed' branch (mainly Python 3.8 update)

### PR DESCRIPTION
**Pull request by tom93**
_DO NOT MERGE. This pull request is only for discussion; the changes need to be applied using git._

Some of the [recent commits](https://github.com/NZOI/nztrain/compare/c9aa70932755bbe7d96397c4dbd5ab62122f126b...66e4393423cddee2576fa02bdca1ae0859acb2ec) on the 'deployed' branch were not quite ready. Specifically, the Python installation scripts have some syntax errors. I'd also like to try to clean up the history a little bit if that's all right with everyone.

I propose to reset the 'deployed' branch from commit 66e4393423cddee2576fa02bdca1ae0859acb2ec back to commit c9aa70932755bbe7d96397c4dbd5ab62122f126b, then work on the pull requests and re-merge them.

Since resetting a branch can potentially lose commits and cause problems with other work based on that branch, I wanted to have a discussion first and make sure everyone is OK with this. I propose a 24 hour feedback period, and if no one objects I'll then reset the 'deployed' branch and force-push.

To make things easier, please don't merge in new pull requests into the 'deployed' branch or base work on the commits in question until this pull request is closed.

### CODE REVIEW

**Comment by puqeko** [comment]
Is it worth the risk of loosing commits and maybe breaking the server just to have a clean history?

I feel like it would be safer and easier to create new commits that apply patches - and make improvements to the merge process to prevent this happening again.

Regards the mistakes. It's my fault for being too hasty with merging. I'm sorry. Is there a way on Github to signify that a branch is ready for merging? Perhaps we could require that someone other than the PR author approve a merge first?

**Comment by lambda-fairy** [comment]
> Is it worth the risk of loosing commits and maybe breaking the server just to have a clean history?

It's not as risky as you think. Git keeps old commits for 30 days. Within that time, it is easy to fish old commits back out if you accidentally lose them.

> Perhaps we could require that someone other than the PR author approve a merge first?

Sounds good to me. At work, every PR is blocked on build passing + one approval.

I think GitHub has a feature to enforce this, actually. But I don't have permission to check.

**Comment by puqeko** [comment]
> It's not as risky as you think.

Okay, if you guys think it's safe then you're welcome to go ahead.

> I think GitHub has a feature to enforce this

There is so. I have enabled it on `deployed` and `master` (hopefully). However, admins can override

**Comment by tom93** [comment]
I created a branch called 'deployed-backup' with the current version of 'deployed' to avoid any risk of lost commits.

If we reset the branch on GitHub but don't reset it on the server until all the commits have been re-merged there is no risk of breaking the server (it's hard to reset a branch by accident).

A clean history is pretty important to me (I often look back through it and have to make sense of it each time). I guess the cost is to wait a little while I clean up (or be prepared to rebase work).

I'll try to improve my reviewing habits and explicitly use "Approve" or "Request changes" instead of just the "Comment" option.

**Comment by puqeko** [comment]
Okay, sounds good to me. Let me know if there is anything else I can change and/or do differently too. I agree that it's nice being able to read back through the history and figure out how something was built/changed. I'll refrain from committing until you are done.

@Holmes98 Are you good to go on this? It's only really the four of us who are active

**Comment by Holmes98** [comment]
Go ahead. I'd also prefer the history to be cleaner.

**Comment by Holmes98** [comment]
See #58.

**Comment by tom93** [comment]
Thanks everyone for humouring me, I'll try not to make this a regular thing.

**Pull request closed without merging**
