### PR TITLE
Add & configure sentry-raven

### PR DESCRIPTION
**Pull request by bagedevimo**
Use the Settings table to store the DSN to prevent it leaking to the
entire world via the source code. Once we have better env or secret
management we should migrate to that.

### CODE REVIEW

**Comment by bagedevimo** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/221?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #198** <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #199** <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/199?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #221** <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/221?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
      * **PR #200** <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/200?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/NZOI/nztrain/221?utm_source=stack-comment).

**Comment by tom93** [comment]
I'm not familiar with sentry-raven, but from the [docs](https://github.com/getsentry/sentry-ruby#migrate-from-sentry-raven) it sounds like it has been replaced with sentry-ruby...

**Comment by bagedevimo** [comment]
You're 100% correct, but sentry-ruby / sentry-rails require more modern versions of both ruby & rails, and it'd be really nice to have to error reporting while we upgrade to those versions.

**Comment by tom93** [comment]
Aside: Just noticed we already have the gem because qless depends on it.

**Comment by tom93** [comment]
@bagedevimo I rebased and force-pushed due to Gemfile.lock conflict with #224. Bundler ended up picking sentry-raven 3.1.2 instead of 0.15.6. I also modified the comment to mention the native SENTRY_DSN env var.

**Review by tom93 — APPROVED** [review]
Not sure how to test this, but seems fine.

**Pull request merged**
