### PR TITLE
Add standardrb and generate a todo file

### PR DESCRIPTION
**Pull request by bagedevimo**
Brief discussion on Discord garnered no hatred for the idea of using a
linter, and it can be aspirational - we move towards standard slowly :)

### CODE REVIEW

**Comment by bagedevimo** [comment]
Current dependencies on/for this PR:
* `master`
  * **PR #215** <a href="https://app.graphite.dev/github/pr/NZOI/nztrain/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/NZOI/nztrain/215?utm_source=stack-comment).

**Review by tom93 — COMMENTED** [review]
FYI, the deps are broken (ruby 2.3.8):

```
$ bundle install
Resolving dependencies...
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 1.6.13)

  In Gemfile:
    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      actionpack (= 4.1.16) was resolved to 4.1.16, which depends on
        rack (~> 1.5.2)

    better_errors was resolved to 2.9.1, which depends on
      rack (>= 0.9.0)

    capybara was resolved to 2.17.0, which depends on
      rack (>= 1.0.0)

    sinatra was resolved to 1.4.8, which depends on
      rack (~> 1.5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by bagedevimo** [comment]
yep, my environment is getting too confusing, so i'll wait for some more stuff to merge. it also needs rails 4.2 and ruby 2.4 so may as well just wait for those.

**Comment by tom93** [comment]
I wanted to try it out, it worked for me when I installed it using `bundle add standard -g development,test` (it picked standard 0.2.5).

**Comment by bagedevimo** [comment]
oh well fuck, force push over this branch?

**Comment by tom93** [comment]
Wait what?

**Comment by bagedevimo** [comment]
haha sorry, i just mean i couldn't get it working on ruby 2.3 properly. so feel free to commit your changes to this branch and force-push over my commit

**Comment by tom93** [comment]
I just posted that in case other people wanted to try standard, but I guess we might as well switch to the old version instead of waiting.
(I'll also switch from "standardrb" to "standard" if that's okay -- the first is an alias for the second, their docs use the second and say the "rb" suffix is just because there was an existing CLI tool with the name "standard".)

**Comment by bagedevimo** [comment]
please do - i just have it called "standardrb" in my head because we also use "standardjs" at work :)

**Comment by tom93** [comment]
On my trivial unrelated PR (#216), standard 0.2.5 [suggested](https://github.com/NZOI/nztrain/pull/216/commits/c46649a6aa73ed8cbc402c1720d84b09e14155ea) `if !...` => `unless ...` while standard 1.32.1 didn't complain.
Do you have a preference in this particular case?
And more generally, should we skip the older version of standard to reduce formatting changes?
(We could manually install a new version of standard using a new version of Ruby, without going through the Gemfile and bundler.)

**Comment by bagedevimo** [comment]
i'm pretty ambivalent, i doubt we're going to fix everything in _todo.yml before we can update standardrb

**Review by tom93 — APPROVED** [review]
I force-pushed some changes:
 - 1.0.5 => 0.2.5 (for Ruby 2.3 compat)
 - .standard_todo.yml => .standard.yml (since _todo.yml requires 0.4.0; added a TODO comment to rename)
 - standardrb => standard (as discussed)

**Comment by tom93** [comment]
A little late, but should we also add the `standard-rails` gem?

**Comment by bagedevimo** [comment]
Unfortunately not - I would have if I could - it has a dependency on ruby 2.6 https://rubygems.org/gems/standard-rails/versions/0.0.1

**Pull request merged**
